chore: add primary button
savannahghi/myafyahub pull request #20
Opened 2021-09-27 09:44 UTC by Paulmburu

![Screenshot_1632735282](https://user-images.githubusercontent.com/24954467/134884640-e5f7bd02-98ad-4e57-97da-d9cc52d452aa.png)

2021-09-27 12:52 UTC, abiudorina requested changes
There is a grey outline

2021-09-27 12:52 UTC, abiudorina commented on lib/presentation/core/widgets/my_afya_hub_primary_button.dart
> +            color: borderColor ?? Theme.of(context).accentColor,
Remove this color, it is what is causing the green outline in the button. 
![image](https://user-images.githubusercontent.com/60188019/134911234-5d4f703e-a92e-420e-8e7d-8197945792be.png)

2021-09-27 12:52 UTC, abiudorina commented on test/widgets_tests/presentation/core/widgets/buttons_test.dart
> +      const Key buttonKey = Key('button_key');
Optimize this test. There is no need for this key because the button is the only one in the widget tree after pumping.

remove it and find the button by it's type

2021-09-28 18:51 UTC, abiudorina approved these changes

2021-09-29 07:19 UTC, abiudrn requested changes

2021-09-29 07:19 UTC, abiudrn commented on lib/presentation/core/widgets/my_afya_hub_primary_button.dart
> +typedef OnPressed = Function(String val);
Move this typedef into a common location.

2021-09-29 08:00 UTC, abiudrn approved these changes

2021-09-29 08:00 UTC, merged