chore: add otp_code_fied_widget
savannahghi/myafyahub pull request #22
Opened 2021-09-27 10:57 UTC by EugeneDevv

2021-09-27 11:04 UTC, EugeneDevv commented
![Screenshot_20210927-135401](https://user-images.githubusercontent.com/52879659/134896597-229eb521-0543-4093-8f13-de2d2374a359.png)

2021-09-27 13:58 UTC, johnngugi approved these changes

2021-09-27 14:07 UTC, abiudorina requested changes

2021-09-27 14:07 UTC, abiudorina commented on lib/presentation/core/widgets/otp_code_field_widget.dart
> +        //highlightAnimation: true,
Remove dead code

2021-09-27 14:07 UTC, abiudorina commented on lib/presentation/core/widgets/otp_code_field_widget.dart
> +// ignore: prefer_function_declarations_over_variables
Remove this linting exclusion and fix the code. For more information, consult the linter docs at [here](https://dart-lang.github.io/linter/lints/prefer_function_declarations_over_variables.html)

2021-09-27 14:07 UTC, abiudorina commented on lib/presentation/core/widgets/otp_code_field_widget.dart
> +class PinCodeOtpField extends StatelessWidget {
Since we are making these components from scratch, let's do them right. Change this from `PinCodeOtpField` to `PINInputField`.

2021-09-28 06:00 UTC, EugeneDevv commented
![Screenshot_20210928-083620](https://user-images.githubusercontent.com/52879659/135031641-e1fa2c38-1d2a-436b-b0e2-723d706b8748.png)

2021-09-28 07:18 UTC, johnngugi approved these changes

2021-09-28 07:19 UTC, johnngugi approved these changes

2021-09-28 18:42 UTC, abiudrn approved these changes

2021-09-28 18:50 UTC, abiudorina approved these changes

2021-09-28 18:52 UTC, merged