chore: hook bookmark content to api
savannahghi/myafyahub pull request #354
Opened 2021-11-30 15:57 UTC by EugeneDevv

2021-11-30 17:15 UTC, abiudrn approved these changes

2021-12-01 07:13 UTC, abiudrn requested changes

2021-12-01 07:13 UTC, abiudrn commented on lib/application/redux/actions/bookmark_content_action.dart
> +    }
2 comments here:

1. `_client.parseError(body)` returns a string containing the actual error. You can pass it into L62
2. Add a more meaningful error message on L66

2021-12-01 07:13 UTC, abiudrn commented on lib/application/redux/actions/bookmark_content_action.dart
> +          content: Text('Error saving content, try again later'),
This error message needs to be more user friendly

2021-12-01 07:13 UTC, abiudrn commented on lib/application/redux/actions/bookmark_content_action.dart
> +          duration: Duration(seconds: 2),
The duration needs to be longer than 5 seconds so that the user has enough time to read

2021-12-01 11:54 UTC, EugeneDevv commented on lib/application/redux/actions/bookmark_content_action.dart
> +          content: Text('Error saving content, try again later'),
I've changed it to generic one for now. Is it okay if I directly display the error returned by the api?

2021-12-01 12:26 UTC, abiudrn approved these changes

2021-12-01 12:26 UTC, merged