chore: restore congrats page links
savannahghi/myafyahub pull request #380
Opened 2021-12-09 11:51 UTC by EugeneDevv

2021-12-09 13:20 UTC, Paulmburu approved these changes

2021-12-09 13:33 UTC, KellyEgesa requested changes

2021-12-09 13:33 UTC, KellyEgesa commented on lib/presentation/onboarding/set_nickname/pages/congratulations_page.dart
> +                      StoreConnector<AppState, AppStateViewModel>(
Remove this, It is repetition

2021-12-09 13:40 UTC, EugeneDevv commented
![shot1](https://user-images.githubusercontent.com/52879659/145406861-2afead42-2e73-43cf-b5a3-66dc1cab6b7a.png)
![shot2](https://user-images.githubusercontent.com/52879659/145406865-4d4003a9-bfff-4cbb-920c-cad2ec76e687.png)

2021-12-09 13:49 UTC, KellyEgesa approved these changes

2021-12-10 02:45 UTC, johnngugi requested changes

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/content/pages/content_details_page.dart
> +    final Widget publishDate = payload.content.metadata!.createdAt!.isNotEmpty
Potential for app crashing due to the null assertion operators

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/content/pages/content_details_page.dart
> +                    thumbnail: payload.content.heroImage!.url!,
Avoid null assertion operators

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/content/pages/content_details_page.dart
> +                        payload.content.heroImage!.url!,
null assertion operators

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/content/pages/content_details_page.dart
> +                      estimateReadTime: payload.content.estimate!,
Same as before

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/content/pages/content_details_page.dart
> +                          contentID: payload.content.contentID!,
Same as before

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/content/widgets/mini_content_widget.dart
> +            .pushNamed(BWRoutes.contentDetailPage, arguments: ContentDetails(content: contentDetails!, showReactions: false)),
Same as before

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/onboarding/set_nickname/pages/congratulations_page.dart
> +                  : () async {
Extract this into a named function

2021-12-10 02:45 UTC, johnngugi commented on lib/presentation/onboarding/set_nickname/pages/congratulations_page.dart
> +                      if (!InternetConnectivitySubject()
`InternetConnectivitySubject` is no longer used. Refer to [this](https://github.com/savannahghi/myafyahub/blob/5adb026206086f4afb9716da1e8ea8ce266193b9/lib/presentation/onboarding/login/pages/login_page.dart#L190) to see how connectivity is checked

2021-12-10 07:39 UTC, johnngugi approved these changes

2021-12-10 07:43 UTC, KellyEgesa approved these changes

2021-12-10 08:40 UTC, merged