chore: feed filter item
savannahghi/myafyahub pull request #39
Opened 2021-09-30 11:21 UTC by Paulmburu

![Screenshot_1632999866](https://user-images.githubusercontent.com/24954467/135446118-86bf4e69-27c0-4177-829a-432a903e46ee.png)

2021-10-01 13:08 UTC, johnngugi approved these changes

2021-10-01 13:11 UTC, abiudrn requested changes

2021-10-01 13:11 UTC, abiudrn commented on test/widgets_tests/presentation/core/widgets/filters/feed_item_filter_test.dart
> +      await tester.pumpAndSettle();
How can we verify that thing onTap() is actually being called here?

2021-10-04 06:16 UTC, abiudrn approved these changes

2021-10-04 06:46 UTC, merged