feat: reset pin
savannahghi/myafyahub pull request #412
Opened 2022-01-11 08:43 UTC by Paulmburu

- implement reset pin on expiry

2022-01-12 09:42 UTC, johnngugi requested changes

2022-01-12 09:42 UTC, johnngugi commented on lib/application/redux/actions/send_otp_action.dart
> +        StoreProvider.state<AppState>(context)?.onboardingState?.isResetPin ??
Access state directly instead of through storeprovider

2022-01-12 14:03 UTC, johnngugi requested changes

2022-01-12 14:03 UTC, johnngugi commented on lib/application/core/services/onboarding_utils.dart
> +      Navigator.pushNamed(
I think navigation should occur within the action instead of inside this function

2022-01-13 14:13 UTC, johnngugi requested changes

2022-01-13 14:13 UTC, johnngugi commented on lib/application/core/services/onboarding_utils.dart
> +  String? phoneNumber,
Is the phoneNumber param being used?

2022-01-13 14:16 UTC, Paulmburu commented on lib/application/core/services/onboarding_utils.dart
> +  String? phoneNumber,
not really, let me get rid of it

2022-01-13 14:18 UTC, johnngugi approved these changes

2022-01-14 06:32 UTC, EugeneDevv approved these changes

2022-01-14 06:52 UTC, merged