chore: notifications page
savannahghi/myafyahub pull request #45
Opened 2021-10-01 12:39 UTC by KellyEgesa

2021-10-01 13:32 UTC, KellyEgesa commented
![f08fed35-8c3e-4907-8398-cf905f652204](https://user-images.githubusercontent.com/40017946/135628540-a4bfd203-f9a6-4f21-8e4e-04916a1da133.jpeg)

2021-10-04 20:50 UTC, abiudrn requested changes

2021-10-04 20:50 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +List<Map<String, dynamic>> notifications = <Map<String, dynamic>>[
A f questions...

1. should this data be in the strings file?
2. shouldn't this be a list of serialized data objects?

2021-10-04 20:50 UTC, abiudrn commented on lib/domain/core/value_objects/app_strings.dart
> +List<Map<String, dynamic>> notifications = <Map<String, dynamic>>[
I also haven't seen where this data is being used.

2021-10-05 08:08 UTC, abiudrn approved these changes

2021-10-05 08:08 UTC, merged