chore: pin input page
savannahghi/myafyahub pull request #48
Opened 2021-10-04 09:43 UTC by EugeneDevv

2021-10-04 10:17 UTC, EugeneDevv commented
![em3](https://user-images.githubusercontent.com/52879659/135834348-f7f80c65-a050-4195-9ad2-68486703fda3.png)

2021-10-05 07:34 UTC, EugeneDevv commented
![m5](https://user-images.githubusercontent.com/52879659/135979767-c93a67c4-202f-4ce0-bf41-a3aba173012d.png)

2021-10-05 08:29 UTC, abiudrn requested changes

2021-10-05 08:29 UTC, abiudrn commented on lib/presentation/onboarding/login/pages/pin_input_page.dart
> +      body: SafeArea(
this `SafeArea` widget is not necessary. remove it

2021-10-05 08:29 UTC, abiudrn commented on lib/presentation/onboarding/login/pages/pin_input_page.dart
> +          color: AppColors.timeLineBackgroundColor,
the scaffold has a `backgroundColor` property instead. use it and remove this container

2021-10-05 08:29 UTC, abiudrn commented on lib/presentation/onboarding/login/pages/pin_input_page.dart
> +                          bottom: MediaQuery.of(context).size.height * 0.009),
this is a bit too specific. use a general value like 10.

2021-10-05 08:29 UTC, abiudrn commented on lib/presentation/onboarding/login/pages/pin_input_page.dart
> +                          bottom: MediaQuery.of(context).size.height * 0.009),
Apply this change for the other calculated fields in this page

2021-10-05 08:29 UTC, abiudrn commented on lib/presentation/onboarding/login/widgets/key_pad_widget.dart
> +            style: const TextStyle(
use `TextThemes` for text styling instead

2021-10-05 08:33 UTC, abiudrn commented
General comments:

1. I haven't seen an implementation for `Too many retries`
2. The appbar UI seems off according to the original design

2021-10-05 10:14 UTC, EugeneDevv commented
![too_manytries](https://user-images.githubusercontent.com/52879659/136004484-2956e6a8-5789-44d3-9099-f53f87e42306.png)

2021-10-05 10:15 UTC, EugeneDevv commented
![wrong_pin](https://user-images.githubusercontent.com/52879659/136004537-2d3f0b3c-6a26-43b1-ac47-7dcdb1309d66.png)

2021-10-06 09:23 UTC, merged