chore: try again button functionality
savannahghi/myafyahub pull request #546
Opened 2022-03-19 11:11 UTC by EugeneDevv

2022-03-19 11:20 UTC, abiudrn requested changes

2022-03-19 11:20 UTC, abiudrn commented on lib/presentation/router/router_generator.dart
> +          builder: (_) => VerifySecurityQuestionsHelpPage(),
Revert this change

2022-03-21 08:55 UTC, abiudrn approved these changes

2022-03-21 08:57 UTC, Paulmburu approved these changes

2022-03-21 08:57 UTC, merged