feat: medical data
savannahghi/myafyahub pull request #582
Opened 2022-04-01 09:16 UTC by Paulmburu

2022-04-01 13:29 UTC, johnngugi approved these changes

2022-04-01 13:31 UTC, EugeneDevv approved these changes

2022-04-01 13:34 UTC, abiudrn requested changes

2022-04-01 13:34 UTC, abiudrn commented on lib/application/core/graphql/queries.dart
> +      ValueString
You are requesting the viral load twice. You've already done it in L377

2022-04-01 13:34 UTC, abiudrn commented on lib/application/redux/actions/medical_data/fetch_medical_data_action.dart
> +    final Response response =
Add a check here that verifies that the `fhirPatientID` is not `UNKNOWN`

2022-04-01 13:34 UTC, abiudrn commented on lib/domain/core/entities/medical_data/medical_data_details.dart
> +        id: UNKNOWN,
What are we using the ID for?

2022-04-01 13:34 UTC, abiudrn commented on lib/presentation/profile/medical_data/medical_data_page.dart
> +              final MedicalDataDetails? cd4Count = vm.medicalData?.cd4Count;
You can have them default to `MedicalDataDetails.initial()` so that you won't have to check for their `nullness` in L61 below
```suggestion
              final MedicalDataDetails alergies = vm.medicalData?.allergies ?? MedicalDataDetails.initial();
              final MedicalDataDetails viralLoad = vm.medicalData?.viralLoad ?? MedicalDataDetails.initial();
              final MedicalDataDetails bmi = vm.medicalData?.bmi ?? MedicalDataDetails.initial();
              final MedicalDataDetails cd4Count = vm.medicalData?.cd4Count ?? MedicalDataDetails.initial();
```

2022-04-01 14:36 UTC, abiudrn requested changes

2022-04-01 14:36 UTC, abiudrn commented on test/mocks.dart
> +};
Confirm the structure of this data from the backend.


Also add weight

2022-04-02 09:33 UTC, abiudrn approved these changes

2022-04-02 09:40 UTC, EugeneDevv approved these changes

2022-04-02 10:07 UTC, merged