fix: handle exceptions thrown while setting a nickname
savannahghi/myafyahub pull request #600
Opened 2022-04-05 08:51 UTC by johnngugi

2022-04-05 14:04 UTC, abiudrn requested changes

2022-04-05 14:04 UTC, abiudrn commented on lib/application/redux/actions/set_nickname_action.dart
> +    if (processed.ok) {
Is this necessary? considering the API call being made is a GraphQL call which always returns a 200

2022-04-06 06:46 UTC, johnngugi commented on lib/application/redux/actions/set_nickname_action.dart
> +    if (processed.ok) {
Not necessarily. The underlying client can timeout which returns status code 408.

2022-04-06 07:00 UTC, abiudrn approved these changes

2022-04-06 07:01 UTC, EugeneDevv approved these changes

2022-04-06 07:04 UTC, byronkimani approved these changes

2022-04-06 07:12 UTC, merged