feat: send push token to backend
savannahghi/myafyahub pull request #612
Opened 2022-04-07 12:03 UTC by johnngugi

2022-04-07 12:04 UTC, EugeneDevv approved these changes

2022-04-07 12:07 UTC, byronkimani approved these changes

2022-04-07 12:30 UTC, abiudrn requested changes

2022-04-07 12:30 UTC, abiudrn commented on lib/application/redux/actions/set_push_token_action.dart
> +    await client.query(setPushTokenMutation, <String, dynamic>{'token': token});
Add safety checks here to handle issues when the token was not saved

2022-04-08 10:44 UTC, abiudrn approved these changes

2022-04-08 10:47 UTC, abiudrn approved these changes

2022-04-08 10:57 UTC, merged